/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_github_xmuyulab_sparkStarSolo_adapter_SoloInit */

#ifndef _Included_com_github_xmuyulab_sparkStarSolo_adapter_SoloInit
#define _Included_com_github_xmuyulab_sparkStarSolo_adapter_SoloInit
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_xmuyulab_sparkStarSolo_adapter_SoloInit
 * Method:    runSolo
 * Signature: (Ljava/lang/String;[Ljava/lang/String;[Ljava/lang/String;[[B)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_github_xmuyulab_sparkStarSolo_adapter_SoloInit_runSolo
  (JNIEnv *, jobject, jobjectArray, jobjectArray, jobjectArray, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
