/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_github_xmuyulab_sparkStarSolo_jstar_HeadFile */

#ifndef _Included_com_github_xmuyulab_sparkStarSolo_jstar_HeadFile
#define _Included_com_github_xmuyulab_sparkStarSolo_jstar_HeadFile
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_xmuyulab_sparkStarSolo_jstar_HeadFile
 * Method:    solo
 * Signature: ([[C[[C[[C[Ljava/lang/String;[Ljava/lang/String;)[[C
 */
JNIEXPORT jobjectArray JNICALL Java_com_github_xmuyulab_sparkStarSolo_jstar_HeadFile_solo
  (JNIEnv *, jobject, jobjectArray, jobjectArray, jobjectArray, jobjectArray, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
